apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-jfow
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-guum-tenant/rhtap-demo-app/hacbs-test-project-jfow@sha256:c5c72100f1223d9f258397caa4d6b6a9e1a4da947646dee4b298c608de36de75
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
