apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-jfow
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-jfow
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-jfow
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-jfow
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-jfow
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-guum-tenant/rhtap-demo-app/hacbs-test-project-jfow@sha256:c5c72100f1223d9f258397caa4d6b6a9e1a4da947646dee4b298c608de36de75
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
